create database pizzahut;
use pizzahut;

create table orders(
order_id int not null,
order_date date not null,
order_time time not null,
primary key(order_id) );

create table order_details (
order_details_id int not null,
order_id int not null,
pizza_id text not null,
quantity int not null,
primary key(order_details_id) );

select * from pizzas;
select * from pizza_types;
select * from orders;
select * from order_details;

-- calculate the total revenue generated by pizaa sales
select sum(price * quantity) as total_sales
from order_details o 
join pizzas p on p.pizza_id = o.pizza_id;


-- identify highest price pizza
select name, price from pizza_types p
join pizzas o on p.pizza_type_id = o.pizza_type_id
order by price desc limit 2;

-- identify most commonly used size pizaa

select size,count(order_details_id)  as order_count from pizzas p 
join order_details o on p.pizza_id = o.pizza_id
group by size
order by order_count desc ;

-- select top 5 most ordered pizzas along with their quantities 
SELECT z.name, SUM(o.quantity) AS total_quantity
FROM pizza_types z
JOIN pizzas p
ON z.pizza_type_id = p.pizza_type_id
JOIN order_details o
ON o.pizza_id = p.pizza_id
GROUP BY z.name
ORDER BY total_quantity DESC
LIMIT 5;

########################### INTERMIDIATE #######################
select * from pizzas;
select * from pizza_types;
select * from orders;
select * from order_details;

-- join necesary columns to find the total quantity of each pizaa category ordered
select category, sum(quantity)  as  categorical from pizza_types z
join pizzas p on z.pizza_type_id = p.pizza_type_id
join order_details o on o.pizza_id = p.pizza_id
group by category
order by categorical;

-- determine the distributions od orders according to hours of the day
select hour(order_time),count(order_id) from orders
group by hour(order_time);

-- Join relevant tables to find the category-wise distribution of pizzas.
select category , count(name) from pizza_types
group by category;

-- group the orders by date and calculate the avg numbers of pizzas ordered per day
-- mhnje eka divsala avg kiti orders hotat 
select avg(total_quantity) from  (select order_date, sum(quantity) as total_quantity from orders r
join order_details o on o.order_id = r.order_id
group by order_date) as order_quan;

-- top 3 most ordered pizzas based on revenue
select name,
sum(quantity * price) as revenue
from pizza_types z join pizzas p
on p.pizza_type_id = z.pizza_type_id
join order_details o
on o.pizza_id = p.pizza_id
group by z.name order by revenue desc limit 3;

-- calculate the percentage contribution of each pizza type in total revenue
SELECT category,
    SUM(quantity * price) /
    (
        SELECT SUM(quantity * price)
        FROM pizzas p
        JOIN order_details o
        ON o.pizza_id = p.pizza_id
    ) * 100 AS revenue
FROM pizza_types z
JOIN pizzas p
ON p.pizza_type_id = z.pizza_type_id
JOIN order_details o
ON o.pizza_id = p.pizza_id
GROUP BY category
ORDER BY revenue DESC;

-- analyze the cumulative revenue generated over time
SELECT order_date,
SUM(revenue) OVER (ORDER BY order_date) AS cum_revenue
FROM
(
    SELECT o.order_date,
           SUM(od.quantity * p.price) AS revenue
    FROM order_details od
    JOIN pizzas p
    ON od.pizza_id = p.pizza_id
    JOIN orders o
    ON od.order_id = o.order_id
    GROUP BY o.order_date
) AS sales;

-- determine the top 3  revenue based pizzas based on each category 
SELECT name, revenue
FROM
(
    SELECT category,
           name,
           revenue,
           RANK() OVER(PARTITION BY category ORDER BY revenue DESC) AS rn
    FROM
    (
        SELECT z.category,
               z.name,
               SUM(o.quantity * p.price) AS revenue
        FROM pizza_types z
        JOIN pizzas p
        ON z.pizza_type_id = p.pizza_type_id
        JOIN order_details o
        ON o.pizza_id = p.pizza_id
        GROUP BY z.category, z.name
    ) AS a
) AS b
WHERE rn <= 3;


-- Calculate the total revenue generated in each month.
SELECT
    MONTHNAME(o.order_date) AS month,
    SUM(od.quantity * p.price) AS total_revenue
FROM orders o
JOIN order_details od
ON o.order_id = od.order_id
JOIN pizzas p
ON od.pizza_id = p.pizza_id
GROUP BY MONTH(o.order_date), MONTHNAME(o.order_date)
ORDER BY MONTH(o.order_date);

-- Find the highest-selling pizza for every pizza size.
SELECT size, name, total_quantity
FROM
(
    SELECT
        p.size,
        pt.name,
        SUM(od.quantity) AS total_quantity,
        RANK() OVER(PARTITION BY p.size ORDER BY SUM(od.quantity) DESC) AS rn
    FROM pizzas p
    JOIN pizza_types pt
    ON p.pizza_type_id = pt.pizza_type_id
    JOIN order_details od
    ON od.pizza_id = p.pizza_id
    GROUP BY p.size, pt.name
) AS ranked
WHERE rn = 1;


-- Find the average amount spent per order.
SELECT
    ROUND(AVG(order_total), 2) AS average_order_value
FROM
(
    SELECT
        od.order_id,
        SUM(od.quantity * p.price) AS order_total
    FROM order_details od
    JOIN pizzas p
    ON od.pizza_id = p.pizza_id
    GROUP BY od.order_id
) AS orders_total;

-- Busiest Day of the Week
SELECT
    DAYNAME(order_date) AS day,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY DAYNAME(order_date)
ORDER BY total_orders DESC;

